{
 "title": "Docker Monitoring",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "window_for_max",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Docker Containers Memory Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"}) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Docker Containers CPU Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{image!=\"\"}[$interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Docker Containers Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Docker Containers CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "vCPU" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{image!=\"\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Docker Containers Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(container_fs_writes_bytes_total{image!=\"\"}[$interval])\n)\n",
     "legendFormat": "Write / {{name}}"
    },
    {
     "expr": "sum by (name) (\n  rate(container_fs_reads_bytes_total{image!=\"\"}[$interval])\n)\n",
     "legendFormat": "Read / {{name}}"
    }
   ]
  },
  {
   "title": "Docker Containers Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{image!=\"\"}[$interval])",
     "legendFormat": "Receive / {{name}}"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{image!=\"\"}[$interval])",
     "legendFormat": "Transmit / {{name}}"
    }
   ]
  },
  {
   "title": "Docker Container Memory Reservation Usage",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(100 - ((container_spec_memory_limit_bytes{name=~\".+\"} - container_memory_usage_bytes{name=~\".+\"})  * 100 / container_spec_memory_limit_bytes{name=~\".+\"}) ) by (name) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Docker Container Memory Usage",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Docker Container Peak Memory Usage",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max_over_time (\n  container_memory_working_set_bytes{name=~\".+\"}[$window_for_max]\n)\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Docker Container Peak CPU Usage",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "vCPU" } },
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{image!=\"\"}[$window_for_max])\n) by (name)\n",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}