{
 "title": "Host Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "top_processes_count", "query": "1,2,3,4,5,10,15,20" }
  ]
 },
 "panels": [
  {
   "title": "Host Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (\n  node_memory_MemAvailable_bytes{instance=\"node-exporter:9100\"}\n  /\n  node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"}\n))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  1 -\n  (\n    sum(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) \n    /\n    sum(rate(node_cpu_seconds_total[5m]))\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\n(\n  1 -\n  node_filesystem_free_bytes{mountpoint=\"/\", fstype!~\"tmpfs|overlay\"}\n  /\n  node_filesystem_size_bytes{mountpoint=\"/\", fstype!~\"tmpfs|overlay\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage History",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$interval])))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Top Processes by CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(\n  $top_processes_count,\n  sum by (groupname) (rate(namedprocess_namegroup_cpu_seconds_total[$interval])) * 100\n  / scalar(count(node_cpu_seconds_total{mode=\"idle\"}))\n)\n",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage History",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\n  1 -\n  (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)\n)\n",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Top Processes by Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(\n  $top_processes_count,\n  namedprocess_namegroup_memory_bytes{memtype=\"resident\"} * 100\n    / scalar(node_memory_MemTotal_bytes)\n)\n",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total[$interval])",
     "legendFormat": "Read / {{device}}"
    },
    {
     "expr": "rate(node_disk_writes_completed_total[$interval])",
     "legendFormat": "Write / {{device}}"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[$interval])",
     "legendFormat": "Downloda / {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total[$interval])",
     "legendFormat": "Upload / {{device}}"
    }
   ]
  }
 ]
}